name: Linux

on:
  - push
  - pull_request

jobs:
  build-linux:
    name: build-linux
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3.3.0
      - name: Run build script
        run: |
          cd build/linux && printf "y" | ./build.sh continuous
      - uses: actions/upload-artifact@v1.0.0
        with:
          name: filament-linux
          path: out/filament-release-linux.tgz

  build-fedora:
    name: build-fedora
    runs-on: ubuntu-22.04
    container: fedora:rawhide

    steps:
      - uses: actions/checkout@v3.3.0
      - name: Install build dependencies
        run: |
          dnf -y install clang cmake ninja-build \
            libcxx-devel libcxxabi-devel libcxx-static libcxxabi-static \
            libXcomposite-devel libXxf86vm-devel libglvnd-devel libXi-devel
      - name: CMake build
        run: |
          export CC=clang
          export CXX=clang++
          cmake . -G Ninja -B build -DBUILD_SHARED_LIBS=ON
          cmake --build build -j$(nproc)
